name: Daily News Trigger

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  restart_space:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space
        run: |
          git clone https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.SPACE_REPO }}
          cd ${{ secrets.SPACE_NAME }}
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit --allow-empty -m "trigger $(date)"
          git push
